//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALMS.MANAGER
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRLeaveRequestDetail
    {
        public int LeaveRequestID { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public string LeaveDescription { get; set; }
        public int LeavesRemaining { get; set; }
        public System.DateTime LeaveRequestFrom { get; set; }
        public System.DateTime LeaveRequestTo { get; set; }
        public string LeaveStatus { get; set; }
        public Nullable<System.DateTime> LeaveRequestCreatedDate { get; set; }
        public Nullable<System.DateTime> LeaveStatusUpdateDate { get; set; }
        public Nullable<long> LeaveStatusUpdatedBy { get; set; }
    }
}
